name = "mekanix"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[[d1_databases]]
binding = "DB"
database_name = "mekanix"
database_id = "f8dbaaf3-4c6b-40d5-9dce-ecaa839780e2"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
SMS_PROVIDER = "console"
PAYMENT_PROVIDER = "simulator"
NODE_ENV = "production"

[observability]
enabled = true
